/**
 * Generated by '@kontent-ai/kontent-model-generator@4.1.0'
 */
export const projectModel = {
  languages: {
    default: {
      codename: 'default',
      name: 'Default project language',
    },
  },
  contentTypes: {
    homepage: {
      codename: 'homepage',
      name: 'Homepage',
      elements: {
        picture: {
          codename: 'picture',
          name: 'Picture',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        body_text: {
          codename: 'body_text',
          name: 'Body text',
        },
      },
    },
    homepage_e40d309: {
      codename: 'homepage_e40d309',
      name: 'Homepage',
      elements: {
        subpages: {
          codename: 'subpages',
          name: 'Subpages',
        },
        untitled_custom_element: {
          codename: 'untitled_custom_element',
          name: 'Untitled custom element',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    page: {
      codename: 'page',
      name: 'Page',
      elements: {
        subpages: {
          codename: 'subpages',
          name: 'Subpages',
        },
        content_34ea6af: {
          codename: 'content_34ea6af',
          name: 'Content',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
        show_in_navigation: {
          codename: 'show_in_navigation',
          name: 'Show in navigation',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
  },
  taxonomies: {},
};
