import { IContentItem, Elements } from "@kontent-ai/delivery-sdk";

/**
 * Generated by '@kontent-ai/kontent-model-generator@4.1.0'
 */
export type Faq = IContentItem<{
  answer: Elements.TextElement;
  question: Elements.RichTextElement;
}>;
