import { IContentItem, Elements } from "@kontent-ai/delivery-sdk";

/**
 * Generated by '@kontent-ai/kontent-model-generator@4.1.0'
 */
export type Homepage = IContentItem<{
  picture: Elements.AssetsElement;
  title: Elements.TextElement;
  bodyText: Elements.RichTextElement;
}>;
