
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homepage extends ContentItem {
    public bodyText!: Elements.RichTextElement;
    public picture!: Elements.AssetsElement;
    public headline!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'body_text') {
                    return 'bodyText';
                }
                return elementName;
            })
        });
    }
}
