import { IContentItem, Elements } from "@kontent-ai/delivery-sdk";

/**
 * Generated by '@kontent-ai/kontent-model-generator@4.1.0'
 */
export type Page = IContentItem<{
  subpages: Elements.LinkedItemsElement<IContentItem>;
  content34ea6af: Elements.RichTextElement;
  content: Elements.LinkedItemsElement<IContentItem>;
  url: Elements.UrlSlugElement;
  showInNavigation: Elements.MultipleChoiceElement;
  title: Elements.TextElement;
}>;
